server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /users/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - name: Path
              args:
                pattern: /payments/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - name: Path
              args:
                pattern: /courses/**
        - id: course-access-service
          uri: lb://course-access-service
          predicates:
            - name: Path
              args:
                pattern: /access/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - name: Path
              args:
                pattern: /reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,env"

  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
