server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: course-access-service
          uri: lb://course-access-service
          predicates:
            - Path=/access/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
