server:
  port: 8084

spring:
  application:
    name: course-access-service
  datasource:
    url: jdbc:h2:mem:courseaccessdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
